import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ folder structure — category order and labels come from
// each folder's _category_.json, page order/labels from each file's frontmatter
// (sidebar_position / sidebar_label / title). See docs/*/_category_.json.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
